package main

import (
	"os"
	"path/filepath"
)

// tmuxConfPath is the config file we source when starting the tmux server
// for the pocket session. Living under ~/.pocket/ so it's separate from
// the user's own ~/.tmux.conf and doesn't interfere with their other
// tmux usage.
func tmuxConfPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".pocket", "tmux.conf")
}

// Content we want in the config file. Kept in sync with the set-option
// calls in ensureSession; having it as a file too makes options apply
// deterministically on server start (regardless of whether helper or
// user's zshrc is first to invoke tmux).
const tmuxConfBody = `# JORAN Pocket — tmux config for the shared 'pocket' session.
# Auto-generated by pocket helper. Edit ~/.pocket/tmux.conf.user and
# source it here if you want personal overrides.

set -g mouse off
set -g status off
set -g history-limit 20000
set -g status-interval 5

# Let Mac Terminal.app's native trackpad scroll show tmux pane history.
# Without this override, tmux enters the alternate screen (smcup/rmcup)
# and Terminal.app converts scroll gestures into arrow keys instead of
# scrolling its own buffer — which means the user's trackpad would
# recall previous shell commands (like ↑ on the keyboard) rather than
# reveal old output. Stripping smcup/rmcup keeps tmux on the main
# screen so Terminal.app captures everything it draws in the normal
# scrollback buffer, and two-finger swipe scrolls as expected.
set -g terminal-overrides 'xterm*:smcup@:rmcup@'

# Largest-client wins: pane grows to match the LARGEST attached client,
# so Mac Terminal.app renders Claude Code natively (full width). The
# helper's PTY tracks pane size via RunPaneSizeWatcher and emits a
# pane_size event to the phone, which CSS-scales its xterm grid to fit
# the viewport. Content is identical to Mac, just visually smaller.
set -g window-size largest

# Nice-to-haves
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g escape-time 10

# Load user overrides if present.
source-file -q ~/.pocket/tmux.conf.user
`

// WriteTmuxConf writes (or refreshes) the tmux config file. Idempotent.
func WriteTmuxConf() error {
	path := tmuxConfPath()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(tmuxConfBody), 0o644)
}
