#!/usr/bin/env bash
# JORAN Pocket — launchd + ttyd + cloudflared installer.
#
# Idempotent. Re-run to regenerate wrappers/plists and restart services.
#
# Installs three user-level launchd services:
#   pocket.tmux.ttyd    ttyd web terminal on 127.0.0.1:8080 → tmux session 'pocket'
#   pocket.tmux.tunnel  cloudflared Quick Tunnel proxy
#   pocket.tmux.watcher extracts the https://*.trycloudflare.com URL; optional iMessage push
#
# Reads:
#   ~/Pocket/auth.txt          user:pass for ttyd basic auth (required)
#   ~/Pocket/imessage-to.txt   optional iMessage recipient (email/phone); if missing, no iMessage
#
# Also installs:
#   ~/.tmux.conf            mobile-friendly tmux config (existing file backed up)
#   ~/Pocket/bin/pocket     the CLI
#   /opt/homebrew/bin/pocket  or /usr/local/bin/pocket (symlink)
#   ~/.claude/skills/pocket/SKILL.md  (if ~/.claude/skills exists)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# --- Paths ---
POCKET_HOME="$HOME/Pocket"
BIN_DIR="$POCKET_HOME/bin"
LOG_DIR="$POCKET_HOME/logs"
AUTH_FILE="$POCKET_HOME/auth.txt"
IMESSAGE_FILE="$POCKET_HOME/imessage-to.txt"
URL_FILE="$POCKET_HOME/current-url.txt"
LAUNCH_AGENTS="$HOME/Library/LaunchAgents"

TTYD_LABEL="pocket.tmux.ttyd"
TUNNEL_LABEL="pocket.tmux.tunnel"
WATCHER_LABEL="pocket.tmux.watcher"

TTYD_PLIST="$LAUNCH_AGENTS/${TTYD_LABEL}.plist"
TUNNEL_PLIST="$LAUNCH_AGENTS/${TUNNEL_LABEL}.plist"
WATCHER_PLIST="$LAUNCH_AGENTS/${WATCHER_LABEL}.plist"

TMUX_SESSION="pocket"
TTYD_PORT=8080

say() { printf '\033[1;36m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m!! \033[0m %s\n' "$*" >&2; }

mkdir -p "$BIN_DIR" "$LOG_DIR" "$LAUNCH_AGENTS"

# --- Preflight: binaries ---
for bin in tmux ttyd ssh; do
  command -v "$bin" >/dev/null 2>&1 || { echo "ERROR: '$bin' not found. Run install.sh first." >&2; exit 1; }
done

TMUX="$(command -v tmux)"
TTYD="$(command -v ttyd)"
BREW_BIN_DIR="$(dirname "$TTYD")"

# --- Preflight: auth ---
if [ ! -s "$AUTH_FILE" ]; then
  echo "ERROR: $AUTH_FILE missing or empty. Run install.sh to set credentials." >&2
  exit 1
fi

# --- Install tmux config ---
TMUX_CONF_SRC="$REPO_ROOT/config/tmux.conf"
TMUX_CONF_DST="$HOME/.tmux.conf"
if [ -f "$TMUX_CONF_SRC" ]; then
  if [ -f "$TMUX_CONF_DST" ] && ! cmp -s "$TMUX_CONF_SRC" "$TMUX_CONF_DST"; then
    BACKUP="$TMUX_CONF_DST.bak.$(date +%Y%m%d-%H%M%S)"
    cp "$TMUX_CONF_DST" "$BACKUP"
    say "Backed up existing ~/.tmux.conf → $BACKUP"
  fi
  cp "$TMUX_CONF_SRC" "$TMUX_CONF_DST"
  say "Installed ~/.tmux.conf"
fi

# --- Stamp & install 'pocket' CLI ---
POCKET_SRC="$REPO_ROOT/bin/pocket"
POCKET_DST="$BIN_DIR/pocket"
if [ -f "$POCKET_SRC" ]; then
  sed "s|__REPO_ROOT__|$REPO_ROOT|g; s|__SETUP_SCRIPT__|$SCRIPT_DIR/setup-services.sh|g" \
    "$POCKET_SRC" > "$POCKET_DST"
  chmod +x "$POCKET_DST"
  say "Installed $POCKET_DST"

  for d in /opt/homebrew/bin /usr/local/bin; do
    if [ -w "$d" ]; then
      ln -sf "$POCKET_DST" "$d/pocket"
      say "Symlinked $d/pocket → $POCKET_DST"
      break
    fi
  done
fi

# --- Install Claude Code skill (optional) ---
if [ -d "$HOME/.claude/skills" ] && [ -f "$REPO_ROOT/skill/SKILL.md" ]; then
  mkdir -p "$HOME/.claude/skills/pocket"
  cp "$REPO_ROOT/skill/SKILL.md" "$HOME/.claude/skills/pocket/SKILL.md"
  say "Installed Claude Code skill → ~/.claude/skills/pocket/"
fi

# --- ttyd wrapper ---
TTYD_WRAPPER="$POCKET_HOME/ttyd-run.sh"
cat > "$TTYD_WRAPPER" <<WRAP
#!/usr/bin/env bash
# Auto-generated by setup-services.sh — re-run installer to regenerate.
export PATH="$BREW_BIN_DIR:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:\$PATH"

CRED="\$(cat "$AUTH_FILE" 2>/dev/null)"
if [ -z "\$CRED" ]; then
  echo "FATAL: no credentials in $AUTH_FILE" >&2
  exit 1
fi

exec "$TTYD" \\
  -c "\$CRED" \\
  --port $TTYD_PORT \\
  --interface 127.0.0.1 \\
  --writable \\
  --base-path / \\
  --terminal-type xterm-256color \\
  --check-origin=false \\
  --max-clients 5 \\
  -t 'titleFixed=JORAN Pocket' \\
  -t fontSize=18 \\
  -t 'fontFamily=JetBrains Mono, SF Mono, Menlo, Consolas, monospace' \\
  -t cursorStyle=bar \\
  -t cursorBlink=true \\
  -t scrollback=10000 \\
  -t disableLeaveAlert=true \\
  -t disableResizeOverlay=true \\
  -t macOptionIsMeta=true \\
  -t drawBoldTextInBrightColors=true \\
  -t lineHeight=1.15 \\
  -t 'theme={"background":"#0b0d12","foreground":"#e6e6e6","cursor":"#f97316","cursorAccent":"#0b0d12","selectionBackground":"#2a3344","black":"#1e1e1e","red":"#ef4444","green":"#22c55e","yellow":"#eab308","blue":"#3b82f6","magenta":"#a855f7","cyan":"#06b6d4","white":"#e6e6e6","brightBlack":"#525252","brightRed":"#f87171","brightGreen":"#4ade80","brightYellow":"#fbbf24","brightBlue":"#60a5fa","brightMagenta":"#c084fc","brightCyan":"#22d3ee","brightWhite":"#fafafa"}' \\
  "$TMUX" new-session -A -s "$TMUX_SESSION"
WRAP
chmod +x "$TTYD_WRAPPER"

# --- Tunnel wrapper ---
# Single-shot SSH reverse tunnel to localhost.run. HTTP/1.1 end-to-end so
# iOS Safari works. We deliberately do NOT auto-reconnect: each run of the
# tunnel yields one fresh URL which is the "one-shot link" the user shares
# via iMessage. When the tunnel dies the URL is invalidated; user re-runs
# `pocket share` for a new one.
TUNNEL_WRAPPER="$POCKET_HOME/tunnel-run.sh"
cat > "$TUNNEL_WRAPPER" <<WRAP
#!/usr/bin/env bash
# Auto-generated by setup-services.sh — re-run installer to regenerate.
export PATH="/usr/bin:/bin:\$PATH"
exec /usr/bin/ssh -T \\
  -o StrictHostKeyChecking=accept-new \\
  -o UserKnownHostsFile="$POCKET_HOME/ssh_known_hosts" \\
  -o ConnectTimeout=15 \\
  -o ServerAliveInterval=30 \\
  -o ServerAliveCountMax=6 \\
  -o ExitOnForwardFailure=yes \\
  -o TCPKeepAlive=yes \\
  -o BatchMode=yes \\
  -R 80:localhost:$TTYD_PORT \\
  nokey@localhost.run 2>&1
WRAP
chmod +x "$TUNNEL_WRAPPER"

# --- iMessage helper (no-op if recipient file missing) ---
IMESSAGE_HELPER="$POCKET_HOME/send-imessage.sh"
cat > "$IMESSAGE_HELPER" <<'WRAP'
#!/usr/bin/env bash
msg="${1:-}"
to_file="$HOME/Pocket/imessage-to.txt"
[ -z "$msg" ] && exit 0
[ ! -s "$to_file" ] && exit 0
recipient="$(cat "$to_file")"
[ -z "$recipient" ] && exit 0
escaped="${msg//\"/\\\"}"
/usr/bin/osascript <<APP 2>&1 || true
tell application "Messages"
  try
    set theService to 1st service whose service type = iMessage
    set theBuddy to buddy "$recipient" of theService
    send "$escaped" to theBuddy
  end try
end tell
APP
WRAP
chmod +x "$IMESSAGE_HELPER"

# --- URL watcher ---
WATCHER="$POCKET_HOME/url-watcher.sh"
cat > "$WATCHER" <<WRAP
#!/usr/bin/env bash
set -u
LOG="$LOG_DIR/tunnel.out.log"
CUR="$URL_FILE"
SEND="$IMESSAGE_HELPER"

touch "\$LOG" "\$CUR"
LAST="\$(cat "\$CUR" 2>/dev/null || true)"

/usr/bin/tail -n 200 -F "\$LOG" 2>/dev/null | \\
  /usr/bin/grep --line-buffered -oE 'https://[a-z0-9-]+\.(lhr\.life|trycloudflare\.com|serveo\.net)' | \\
  while read -r url; do
    if [ "\$url" != "\$LAST" ]; then
      LAST="\$url"
      printf '%s\\n' "\$url" > "\$CUR"
      printf '[%s] new URL: %s\\n' "\$(date -Iseconds)" "\$url"
      "\$SEND" "🌐 JORAN Pocket URL 更新了：\$url"
    fi
  done
WRAP
chmod +x "$WATCHER"

# --- Plist writer ---
# keepalive: "always" for the terminal backend (ttyd/tmux/watcher); "ondemand"
# for the SSH tunnel so URLs don't rotate behind the user's back.
write_plist() {
  local label="$1" exe="$2" keepalive="${3:-always}"
  local out="$LAUNCH_AGENTS/${label}.plist"
  local name_suffix="${label##*.}"
  local run_at_load="true" keep_alive="true"
  if [ "$keepalive" = "ondemand" ]; then
    run_at_load="false"
    keep_alive="false"
  fi
  cat > "$out" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>$label</string>
  <key>ProgramArguments</key>
  <array><string>$exe</string></array>
  <key>WorkingDirectory</key><string>$HOME</string>
  <key>RunAtLoad</key><$run_at_load/>
  <key>KeepAlive</key><$keep_alive/>
  <key>ThrottleInterval</key><integer>5</integer>
  <key>ProcessType</key><string>Interactive</string>
  <key>StandardOutPath</key><string>$LOG_DIR/${name_suffix}.out.log</string>
  <key>StandardErrorPath</key><string>$LOG_DIR/${name_suffix}.err.log</string>
</dict>
</plist>
PLIST
}

write_plist "$TTYD_LABEL"    "$TTYD_WRAPPER"    always
write_plist "$TUNNEL_LABEL"  "$TUNNEL_WRAPPER"  ondemand
write_plist "$WATCHER_LABEL" "$WATCHER"         always

# --- Unload old joran services if they're still around ---
for legacy in joran.tmux.ttyd joran.tmux.tunnel joran.tmux.watcher joran.pocket.terminal; do
  launchctl bootout "gui/$UID/$legacy" 2>/dev/null && say "Booted out legacy service: $legacy" || true
  rm -f "$LAUNCH_AGENTS/${legacy}.plist"
done

# --- Unload existing pocket services + reload ---
for label in "$TTYD_LABEL" "$TUNNEL_LABEL" "$WATCHER_LABEL"; do
  launchctl bootout "gui/$UID/$label" 2>/dev/null || true
done
sleep 1
for plist in "$TTYD_PLIST" "$TUNNEL_PLIST" "$WATCHER_PLIST"; do
  launchctl bootstrap "gui/$UID" "$plist"
done

# --- Reload tmux config if session exists ---
if tmux has-session -t "$TMUX_SESSION" 2>/dev/null && [ -f "$HOME/.tmux.conf" ]; then
  tmux source-file "$HOME/.tmux.conf" 2>/dev/null || true
  say "Reloaded tmux config into running '$TMUX_SESSION' session."
fi

echo
echo "=========================================================="
echo " ✅ JORAN Pocket installed (backend services running)."
echo
echo "   The SSH tunnel is NOT started automatically — each tunnel"
echo "   produces a one-shot URL that's good for a single session."
echo
echo "   Start one now:     pocket share"
echo "   Start with TTL:    pocket share --ttl 30m"
echo "   Stop current URL:  pocket stop"
echo "   Service state:     pocket status"
echo "   Attach tmux:       pocket attach"
echo
echo "   Creds are in $AUTH_FILE (mode 600)."
if [ -s "$IMESSAGE_FILE" ]; then
  echo "   iMessage target:  $(cat "$IMESSAGE_FILE")"
fi
echo "=========================================================="
echo
